import type { Metadata } from "next";
import './index.scss'
import './fonts.scss'
import { Navy } from "@/components/navy/Navy";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Navy />
      </body>
    </html>
  );
}
